### PR TITLE
docs: add Japanese README

### PR DESCRIPTION
**Pull request by eltociear**
I created Japanese translated README.

### CODE REVIEW

**Review by AXYZdong — COMMENTED** [review]
Thank you for your contribution!

**Comment by AXYZdong** [comment]
> I created Japanese translated README.

Could you provide a brief introduction of yourself? I will add you to the list of contributors.

**Comment by eltociear** [comment]
@AXYZdong 
Please provide the following information.
```
Board member at I-Tecnology Co., Ltd.
```

**Comment by AXYZdong** [comment]
> Board member at I-Tecnology Co., Ltd.

- eltociear, Board member at I-Tecnology Co., Ltd.

is that ok?

**Comment by eltociear** [comment]
@AXYZdong OK!

**Pull request merged**
